[tool.poetry]
name = "horusdemodlib"
version = "0.4.0"
description = "Project Horus HAB Telemetry Demodulators"
authors = ["Mark Jessop"]
license = "LGPL-2.1-or-later"
include = [
    { path = "horusbinaryv3/HorusBinaryV3.asn1", format = ["sdist", "wheel"] }
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.24.0"
numpy = "^1.17"
python-dateutil = "^2.8"
audioop-lts = { version = "*", python = "^3.13" }
asn1tools = "^0.167.0"
crc = "^7.1.0"

[tool.poetry.group.dev.dependencies]
setuptools = "^80.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
