[tool.poetry]
name = "horusdemodlib"
version = "0.4.0"
description = "Project Horus HAB Telemetry Demodulators"
authors = ["Mark Jessop"]
license = "LGPL-2.1-or-later"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.24.0"
crcmod = "^1.7"
numpy = "^1.17"
python-dateutil = "^2.8"
audioop-lts = { version = "*", python = "^3.13" }
asn1tools = "^0.165.0"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
