name: Horusdemodlib Wheels

on: [push, workflow_dispatch, release]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-15-intel is an Intel runner, macos-14 is Apple silicon
        # macos-15-intel, macos-14
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-15-intel, macos-14]

    steps:
      - uses: actions/checkout@v5

      - run: |
          echo '[build]' > setup.cfg
          echo 'compiler = mingw32' >> setup.cfg
        if: matrix.os  == 'windows-latest'
      - uses: bwoodsend/setup-winlibs-action@v1
        if: matrix.os  == 'windows-latest'
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1
        env:
          CIBW_SKIP: cp38-* pp* *-win32 cp314t-*
          CIBW_BEFORE_BUILD: |
            python3 -m pip install pipx --break-system-packages
            python3 -m pipx ensurepath
            pipx install poetry
            pipx run poetry install
            pipx run poetry build
          CIBW_TEST_COMMAND: python3 -m unittest discover -t {project} -s horusdemodlib -p "*.py"
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  release_test_wheels:
    permissions:
      id-token: write
    needs: [build_wheels]
    name: Release Test Wheels
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  release_prod_wheels:
    permissions:
      id-token: write
    needs: [build_wheels]
    name: Release Producation Wheels
    if: github.event_name == 'release' && github.event.action == 'published'
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1